"""Assemble current framework/language/path support and gap inventory."""
import hashlib,json
from pathlib import Path
from guardcontract.paths import project_root
ROOT=project_root();DIRECTORY=ROOT/"experiments/coverage-inventory-n297"
def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def read(path):return json.loads(Path(path).read_bytes())
def main():
    if DIRECTORY.exists():raise ValueError("coverage297_existing")
    paths={"five":ROOT/"experiments/five-framework-score-n260/SCORES.json","baseline":ROOT/"experiments/family-development-baseline-n296/RESULT.json","split":ROOT/"experiments/prospective-family-split-n294/RESULT.json","readme_yield":ROOT/"experiments/framework-import-yield-n271/RESULT.json","guard_pilot":ROOT/"experiments/prospective-guard-effect-discovery-n283/RESULT.json","registration":ROOT/"experiments/prospective-guard-effect-registration-n284/RESULT.json","session":ROOT/"experiments/session-aware-holdout-n263/RESULT.json","n252":ROOT/"experiments/openai-repair-n252/FAILED.json"};values={k:read(p) for k,p in paths.items()};frameworks={
        "langchain":{"version":"1.4.0","controlled_lifecycles":["post_effect_after_agent","deferred_commit_after_agent"],"controlled_detection_repair_runtime":"supported","repository_wide":"partial_registration_candidate","repair_isolation":"kernel_seccomp"},
        "google-adk":{"version":"2.7.0","controlled_lifecycles":["after_tool_callback","before_tool_callback"],"controlled_detection_repair_runtime":"supported","repository_wide":"partial_registration_candidate","repair_isolation":"kernel_seccomp"},
        "pydantic-ai":{"version":"2.40.0","controlled_lifecycles":["output_validator_post_effect","deferred_commit_in_validator"],"controlled_detection_repair_runtime":"supported","repository_wide":"partial_registration_candidate","repair_isolation":"python_socket_connect_patch_not_kernel"},
        "openai-agents":{"version":"0.22.0","controlled_lifecycles":["parallel_input_guard_race","tool_input_guard"],"controlled_detection_repair_runtime":"supported","repository_wide":"partial_registration_candidate","repair_isolation":"python_socket_connect_patch_after_kernel_timeout"},
        "crewai":{"version":"1.15.18","controlled_lifecycles":["task_output_guardrail","before_tool_hook"],"controlled_detection_repair_runtime":"supported","repository_wide":"partial_registration_candidate","repair_isolation":"python_socket_connect_patch_not_kernel"}}
    result={"schema_version":"guardcontract-coverage-inventory-2","frameworks":frameworks,"languages":{"python":{"controlled_pipeline":"supported","repository_wide":"partial"},"typescript":{"controlled_pipeline":"unsupported","repository_wide":"discovery_only"},"java":{"controlled_pipeline":"unsupported","repository_wide":"discovery_only"},"dotnet":{"controlled_pipeline":"unsupported","repository_wide":"discovery_only"}},"controlled_metrics":values["five"]["detection"]|{"repair":values["five"]["repair"]},"prospective":{"historical_pool_candidates_after_session_exclusion":len(values["session"]["prospective_freeze_candidates"]),"readme_pilot_framework_import_repositories":values["readme_yield"]["counts"]["framework_import_present"],"guard_effect_pilot_explicit_effect_sites":values["guard_pilot"]["counts"]["explicit_effect_sites"],"registration_pilot_routed_jobs":values["registration"]["counts"]["routed_jobs"],"development_families":values["split"]["counts"]["development"],"unread_confirmation_families":values["split"]["counts"]["confirmation"],"development_baseline_unsupported_framework_repositories":values["baseline"]["counts"]["unsupported_framework_repositories"],"development_baseline_explicit_effect_sites":values["baseline"]["counts"]["explicit_effect_sites"]},"unknown_error_policy":{"unsupported_framework":"retained_without_prediction","parse_error":"reported_not_negative","source_truncation":"reported_not_negative","sandbox_timeout":"infrastructure_error_not_repair_failure","llm_unknown":"diagnostic_not_semantic_release_authority"},"saturation":{"consecutive_independent_no_new_family_rounds":0,"required":2,"status":"not_saturated_rounds_one_and_two_added_families"},"holdout":{"eligible":False,"admission_authorized":False,"blocking":["repository-wide analyzers remain partial; complete support absent","effect binding recall uncalibrated","behavior oracle labels absent","direct-related positive and negative oracle coverage not established","non-Python pipeline unsupported"]},"inputs_sha256":{str(p.relative_to(ROOT)):sha(p) for p in [*paths.values(),Path(__file__)]},"goal_completion_proven":False}
    DIRECTORY.mkdir();
    with (DIRECTORY/"RESULT.json").open("x") as handle:json.dump(result,handle,indent=2,sort_keys=True);handle.write("\n")
    print(json.dumps({"frameworks":len(frameworks),"development_families":result["prospective"]["development_families"],"unread_confirmation_families":result["prospective"]["unread_confirmation_families"],"legacy_baseline_unsupported_framework_repositories":result["prospective"]["development_baseline_unsupported_framework_repositories"],"holdout_eligible":False}))
if __name__=="__main__":main()
